# 1. Ligação à Base de Dados (Onde o PostgreSQL mora)
spring.datasource.url=jdbc:postgresql://localhost:5432/cyberlearn
spring.datasource.username=postgres
spring.datasource.password=admin123

# 2. Configurações do Hibernate (JPA)
# 'update' cria/atualiza as tabelas automaticamente com base no teu código Java
spring.jpa.hibernate.ddl-auto=update
# Mostra no terminal os comandos SQL que o Java está a fazer (útil para aprender!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Garante que usamos a "língua" correta do PostgreSQL 
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. Porta do Servidor (Onde vais ver a aplicação no navegador)
server.port=8080